### ISSUE TITLE
Specify the Parent for the project

### ISSUE THREAD

**Issue by oers** [jenkinsci/dependency-track-plugin#139]
## Is your feature request related to a problem? Please describe.
When a new project is created (e.g. a new version is created) the parent cannot be specified,

## Describe the solution you'd like
I would like to either specify the parent of the new project or the system creates it automagically by finding an existing "version" and then making a copy / new version.

Currently I pan to update the "snapshot version" periodically. When I create release I want the plugin to create a new project with a new version under the same parent.

**Comment by msymons** [comment]
I am guessing that this is a request that is aimed at taking advantage of the new parent/child project model introduced in Dependency-Track v4.7.0

As such, it would be a really useful enhancement.   But, @sephiroth-j ,  does the v4.7.0 API contain everything that you would need in order to implement without kludges or performance impact, etc?

**Comment by oers** [comment]
Yes, it is for the parent/child relationship, which really helps to organize different versions for a product.

**Comment by lme-nca** [comment]
@sephiroth-j waiting for this feature, when will the next 4.3.0 version be released ?

**Comment by sephiroth-j** [comment]
Probably this weekend
