### ISSUE TITLE
Produce a report of the dependency track findings

### ISSUE THREAD

**Issue by marioja** [jenkinsci/dependency-track-plugin#147]
## Describe the solution you'd like
Once the result of the findings by Dependency Track are received, Jenkins should produce a report for external forwarding to stakeholders

## Additional context
See PR-146

**Comment by sephiroth-j** [comment]
This feature would make much more sense if it were part of Dependency-Track itself. But this plugin is the wrong place for it. The format of such an export may also vary from company to company. Therefore, there would always be more change requests to include other formats, layouts, etc., which would further bloat the plugin.

The REST-API of DT is pretty well documented and since you have access to the authorization token, you can write you own job to automate the export. In particular, you could use [the export endpoint](https://docs.dependencytrack.org/integrations/file-formats/).

**Comment by marioja** [comment]
I agree with your point that formatting may cause to many change request against the dependency track Jenkins plugin.  I disagree that this feature makes more sense in DT itself.  What do you think about the following suggestion:

The Jenkins Dependency-Track plugin provides a link to a json document including the findings returned from DT after publishing the BOM.  The company using Jenkins could add groovy processing after publishing to take that json and produce the required "company specific" report in whatever format and look and feel.  If you agree I will submit a pull request for this.  Should be a lot simpler.

**Comment by marioja** [comment]
Can you re-open this issue?

**Comment by sephiroth-j** [comment]
> I disagree that this feature makes more sense in DT itself.

Then you might want to think again about the usefulness of such an export function when the underlying data might already be outdated and wrong a few hours after it was saved in Jenkins. DT will always keep them up to date as long as the project is marked as active and has not been deleted. The warning on the results page in Jenkins exists for this reason.

> The Jenkins Dependency-Track plugin provides a link to a json document including the findings returned from DT after publishing the BOM.

There is absolutely no need for this. The results come directly from DT itself and are obtained via its [REST API] (https://docs.dependencytrack.org/integrations/rest-api/). The URL is `/api/v1/finding/project/{projectid}`. All you need is the API key (which you have) and the ID of the project. You may not have the latter, but that's not a problem. Perform a search query to find the project by its name and version using the URL `/api/v1/project/lookup?name={name}&version={version}`.
