### ISSUE TITLE
upstream request timeout when uploading large sbom

### ISSUE THREAD

**Issue by Pabloo-ss** [jenkinsci/dependency-track-plugin#259]
## Describe the bug
When uploading a sbom with ~2100 components I get this error back (attached screenshot)
<img width="1171" alt="Captura de pantalla 2024-07-16 a las 14 10 53" src="https://github.com/user-attachments/assets/a359ef43-f6c0-4507-abcd-367cf75a004e">

## Environment

 - Plugin Version: 4.3.1
 - Jenkins Version: 2.452.2
 - Java Version for Jenkins: openjdk 17.0.11 2024-04-16
 - Type of Jenkins Job: declarative pipeline
 - Dependency-Track Version: 4.11.5
 
## To Reproduce
1. Upload large SBOM
2. Go to Jenkins job
3. See error

## Expected behavior
Successfully uploaded SBOM or at least a polling time out

## Additional context
This is the uploaded SBOM
[sbom_app.json](https://github.com/user-attachments/files/16246156/sbom_app.json)

**Comment by sephiroth-j** [comment]
Well, that's not a problem of the plugin. The response status code is very clear about this: 504 Gateway Timeout. You are likely having some kind of reverse proxy in front of your DTrack API server. This is the place where you have to increase the timeout. You should also check the logs of DTrack because it seems to respond slowly.

p.s.
The upload itself is successful. The timeout then occurs when updating the project properties.
