### ISSUE TITLE
Clone Audit History

### ISSUE THREAD

**Issue by Jonas-vdb** [jenkinsci/dependency-track-plugin#66]
**Issue - Feature Request**
When publishing a new version to Dependency Track of an existing project, the audit history is not cloned. When you add a new version in the UI you have the option to clone various data. Are there properties available to enable this using the Jenkins plugin? (Could be that I overlooked this in the documentation)

![image](https://user-images.githubusercontent.com/10735898/146799309-4482064a-de45-4989-91d7-3aec3f9930ea.png)

**Use case:**
Project v1.0.0 has 15 vulnerabilities. Various audit trails and statuses have been added to the project version. New version Project v1.0.1 is published but all the auditing info needs to be re-added.

**Used Versions**
Dependency-Track  v4.3.6
OWASP Dependency-Track Plugin v4.0.0

**Comment by sephiroth-j** [comment]
For cloning, the ID of the project to be cloned is required. In DT there is no predecessor relationship. The DT frontend knows which project to clone because it uses the currently open project. The Jenkins plugin would either need the ID of the project to clone or would have to look up all the versions with the same project name, sort them somehow, and then make the clone call. This would make things too complicated. Therefore, I reject this feature request.

**Comment by aristotelos** [comment]
> In DT there is no predecessor relationship. The DT frontend knows which project to clone because it uses the currently open project. The Jenkins plugin would either need the ID of the project to clone or would have to look up all the versions with the same project name, sort them somehow, and then make the clone call. This would make things too complicated.

It is indeed slightly complicated because DT allows almost any string as a version. However, I think that many users of DT that are integrating it in CI would like to have this feature. Sadly, there is no guidance in the Dependency Track documentation on how to deal with auditing multiple versions. There is just a feature to clone from an existing project when creating a new project, no other option as far as I can find, so it seems that having this feature in CI is the only way of working if we do not want to fallback to manually copying findings and comments from previous releases.

I suggest that the Jenkins plugin for now would come with a new optional feature that:

1. Parses the version using the https://semver.org format (inability to parse logs a warning and continues without attempt to clone)
2. Find all versions of the parent project and sort them, taking the latest as a preceding version
5. Clone from that version and log that this version was used to be cloned from

I'd like to link https://github.com/DependencyTrack/dependency-track/issues/222 which is related.
